Revert "Web Inspector: Remove support for CSS Regions"
To be able to use new remote inspector with WebKitGTK 2.18.

Otherwise, the following exception occurs:
TypeError:  CSSAgent.getNamedFlowCollection is not a function. (In 'CSSAgent.getNamedFlowCollection(documentNodeIdentifier, onNamedFlowCollectionAvailable.bind(this) ) ', 'CSSAgent.getNamedFlowCollection' is undefined)  (at DOMTreeManager.js: 562: 44)
    getNamedFlowCollection @ DOMTreeManager.js: 562: 44
    ?  @ DOMTree.js: 119: 53
    requestRootDOMNode @ DOMTree.js: 94: 21
    requestContentFlowList @ DOMTree.js: 117: 32
    _rootDOMNodeInvalidated @ FrameTreeElement.js: 290: 55
    dispatch @ Object.js: 170: 30
    dispatchEventToListeners @ Object.js: 177: 17
    performInvalidate @ DOMTree.js: 80: 42
    performInvalidate @ [native code]

This reverts commit 953a2efb093b10cad0e74840d6ee7c750d1892f7.